allowed_labels:
- "Alcohols"
- "Cakes"
- "Dairy"
- "Frozen food and ice cream"
- "Jams, honey"
- "Flakes, musli"
- "Cookies"
- "Chocolates and bars"
- "Cleaning"
- "Coffee"
- "Tea"
- "Drugstore"
- "Hygiene"
- "For pets"
- "Home baking"
- "Loose: Groats, Salt"
- "Tomato preserves"
- "Sauces"
- "Loose: Flour, sugar, pasta"
- "Instant dishes and sauces"
- "Apples and potatoes"
- "Dried fruits, seeds, grains"
- "Canned meat and fish"
- "Sparkling"
- "Crispbreak, gluten-free food"
- "Juices"
- "Herbs and spices"
- "Fruit and vegetable preserves"
- "International cuisine"
- "Fruits and vegatables"
- "Mineral waters"
- "Beers"
- "Oils, olive oils, vinegars"
- "Vegan and organic"
- "Ready to eat"
- "Fish"
- "Bread"
- "Meat and sausage"
- "Cheese"
dir: /home/dzieciou/projects/tree-labeller/demo/marketpoint
original_tree_path: /home/dzieciou/projects/tree-labeller/frisco.yaml
start_time: 2023-01-01 23:02:10.297280
tree_path: /home/dzieciou/projects/tree-labeller/demo/marketpoint/frisco.yaml
