# This is a basic workflow to help you get started with Actions

name: readme2tex-action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [feature/demo]
  pull_request:
    branches: [master2]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install pdflatex and rename
        run: sudo apt install texlive-latex-base rename
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install readme2tex
      - name: Remove previous .svg files
        run: |
          rm -f docs/svgs/*.svg
      - name: Build readmes
        run: |
          find . -type f -name '*.tex.md' -execdir python3 -m readme2tex --readme "{}" --nocdn --output "{}.temp" \;
      - name: Copy built .md files
        run: |
          find . -type f -exec rename -f 's/.tex.md.temp/.md/' '{}' \;
      - name: Commit the built files
        run: |
          git config --global user.name '${{github.repository_owner}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git add -u && git add . && git commit -m "Built the .tex.md files"
          git push